// Package dbprov creates and drops per-site MariaDB databases. Each site gets
// its own user that can only touch its own schema.
package dbprov

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"regexp"
	"strconv"

	"github.com/go-sql-driver/mysql"
)

type MariaDB struct {
	db *sql.DB
}

func Open(dsn string) (*MariaDB, error) {
	cfg, err := mysql.ParseDSN(dsn)
	if err != nil {
		return nil, err
	}
	// DDL statements can't be server-side prepared; let the driver escape
	// placeholders client-side instead.
	cfg.InterpolateParams = true
	db, err := sql.Open("mysql", cfg.FormatDSN())
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(2)
	return &MariaDB{db: db}, nil
}

func (m *MariaDB) Close() error { return m.db.Close() }

// Identifiers can't be bound as parameters, so they are restricted to a
// charset that needs no quoting at all. Names are generated by us, but this
// is the last line of defence against SQL injection via identifiers.
var identRe = regexp.MustCompile(`^[a-z0-9_]{1,32}$`)

func (m *MariaDB) CreateSiteDB(ctx context.Context, name, user, password string) error {
	if !identRe.MatchString(name) || !identRe.MatchString(user) {
		return fmt.Errorf("invalid database identifier")
	}
	stmts := []struct {
		q    string
		args []any
	}{
		{"CREATE DATABASE IF NOT EXISTS `" + name + "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", nil},
		{"CREATE USER IF NOT EXISTS '" + user + "'@'%' IDENTIFIED BY ?", []any{password}},
		{"GRANT ALL PRIVILEGES ON `" + name + "`.* TO '" + user + "'@'%'", nil},
	}
	for _, s := range stmts {
		if _, err := m.db.ExecContext(ctx, s.q, s.args...); err != nil {
			return fmt.Errorf("provision db: %w", err)
		}
	}
	return nil
}

func (m *MariaDB) DropSiteDB(ctx context.Context, name, user string) error {
	if !identRe.MatchString(name) || !identRe.MatchString(user) {
		return fmt.Errorf("invalid database identifier")
	}
	if _, err := m.db.ExecContext(ctx, "DROP DATABASE IF EXISTS `"+name+"`"); err != nil {
		return err
	}
	_, err := m.db.ExecContext(ctx, "DROP USER IF EXISTS '"+user+"'@'%'")
	return err
}

// SetConnectionLimit caps how many MariaDB connections a site's user may
// hold at once. Every site shares one server, so without this a single busy
// (or attacked) site can take all max_connections and knock every other
// site offline with "Error establishing a database connection".
func (m *MariaDB) SetConnectionLimit(ctx context.Context, user string, n int) error {
	if !identRe.MatchString(user) || n < 1 {
		return fmt.Errorf("invalid connection limit for %q", user)
	}
	_, err := m.db.ExecContext(ctx, "ALTER USER '"+user+"'@'%' WITH MAX_USER_CONNECTIONS "+strconv.Itoa(n))
	return err
}

// Table names come from plugins, so they are checked rather than trusted:
// only characters that can't break out of a backquoted identifier.
var tableRe = regexp.MustCompile(`^[A-Za-z0-9_$]{1,64}$`)

// Tables lists the tables of a site database.
func (m *MariaDB) Tables(ctx context.Context, db string) ([]string, error) {
	if !identRe.MatchString(db) {
		return nil, fmt.Errorf("invalid database identifier")
	}
	rows, err := m.db.QueryContext(ctx,
		"SELECT table_name FROM information_schema.tables WHERE table_schema = ? ORDER BY table_name", db)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

// DatabaseSize is the space a site database takes (data and indexes, as
// InnoDB reports them), for disk quotas.
func (m *MariaDB) DatabaseSize(ctx context.Context, db string) (int64, error) {
	if !identRe.MatchString(db) {
		return 0, fmt.Errorf("invalid database identifier")
	}
	var n int64
	err := m.db.QueryRowContext(ctx, "SELECT CAST(COALESCE(SUM(data_length + index_length), 0) AS SIGNED) "+
		"FROM information_schema.tables WHERE table_schema = ?", db).Scan(&n)
	return n, err
}

// DropTables drops tables of a site database (used to undo tables an
// update created when its snapshot is restored).
func (m *MariaDB) DropTables(ctx context.Context, db string, tables []string) error {
	if !identRe.MatchString(db) {
		return fmt.Errorf("invalid database identifier")
	}
	for _, t := range tables {
		if !tableRe.MatchString(t) {
			return fmt.Errorf("refusing to drop table with unusual name %q", t)
		}
		if _, err := m.db.ExecContext(ctx, "DROP TABLE IF EXISTS `"+db+"`.`"+t+"`"); err != nil {
			return err
		}
	}
	return nil
}

// Temporary accounts for database sessions (Adminer): scoped to one site
// database, few connections, dropped when the session ends. Their names
// start with TempUserPrefix, so leftovers of a crash are found and dropped.
const TempUserPrefix = "wpga_"

var tempUserRe = regexp.MustCompile(`^wpga_[a-z0-9]{8,20}$`)

// CreateTempUser creates an account with full rights on one site database.
func (m *MariaDB) CreateTempUser(ctx context.Context, db, user, password string) error {
	if !identRe.MatchString(db) || !tempUserRe.MatchString(user) {
		return fmt.Errorf("invalid temporary account")
	}
	if _, err := m.db.ExecContext(ctx, "CREATE USER '"+user+"'@'%' IDENTIFIED BY ? WITH MAX_USER_CONNECTIONS 5", password); err != nil {
		return err
	}
	if _, err := m.db.ExecContext(ctx, "GRANT ALL PRIVILEGES ON `"+db+"`.* TO '"+user+"'@'%'"); err != nil {
		m.DropTempUser(ctx, user)
		return err
	}
	return nil
}

// DropTempUser drops a temporary account and ends its connections (a
// dropped account's open connections would otherwise keep working).
func (m *MariaDB) DropTempUser(ctx context.Context, user string) error {
	if !tempUserRe.MatchString(user) {
		return fmt.Errorf("invalid temporary account")
	}
	if _, err := m.db.ExecContext(ctx, "DROP USER IF EXISTS '"+user+"'@'%'"); err != nil {
		return err
	}
	rows, err := m.db.QueryContext(ctx, "SELECT ID FROM information_schema.PROCESSLIST WHERE USER = ?", user)
	if err != nil {
		return err
	}
	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return err
		}
		ids = append(ids, id)
	}
	rows.Close()
	for _, id := range ids {
		m.db.ExecContext(ctx, "KILL CONNECTION "+strconv.FormatInt(id, 10)) // may have ended already
	}
	return rows.Err()
}

// DropTempUsers drops every temporary account (at startup: sessions don't
// survive a restart).
func (m *MariaDB) DropTempUsers(ctx context.Context) error {
	rows, err := m.db.QueryContext(ctx, "SELECT User FROM mysql.user WHERE User LIKE 'wpga\\_%'")
	if err != nil {
		return err
	}
	var users []string
	for rows.Next() {
		var u string
		if err := rows.Scan(&u); err != nil {
			rows.Close()
			return err
		}
		users = append(users, u)
	}
	rows.Close()
	var errs []error
	for _, u := range users {
		if tempUserRe.MatchString(u) {
			errs = append(errs, m.DropTempUser(ctx, u))
		}
	}
	return errors.Join(errs...)
}
