// Package dbprov creates and drops per-site MariaDB databases. Each site gets
// its own user that can only touch its own schema.
package dbprov

import (
	"context"
	"database/sql"
	"fmt"
	"regexp"
	"strconv"

	"github.com/go-sql-driver/mysql"
)

type MariaDB struct {
	db *sql.DB
}

func Open(dsn string) (*MariaDB, error) {
	cfg, err := mysql.ParseDSN(dsn)
	if err != nil {
		return nil, err
	}
	// DDL statements can't be server-side prepared; let the driver escape
	// placeholders client-side instead.
	cfg.InterpolateParams = true
	db, err := sql.Open("mysql", cfg.FormatDSN())
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(2)
	return &MariaDB{db: db}, nil
}

func (m *MariaDB) Close() error { return m.db.Close() }

// Identifiers can't be bound as parameters, so they are restricted to a
// charset that needs no quoting at all. Names are generated by us, but this
// is the last line of defence against SQL injection via identifiers.
var identRe = regexp.MustCompile(`^[a-z0-9_]{1,32}$`)

func (m *MariaDB) CreateSiteDB(ctx context.Context, name, user, password string) error {
	if !identRe.MatchString(name) || !identRe.MatchString(user) {
		return fmt.Errorf("invalid database identifier")
	}
	stmts := []struct {
		q    string
		args []any
	}{
		{"CREATE DATABASE IF NOT EXISTS `" + name + "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", nil},
		{"CREATE USER IF NOT EXISTS '" + user + "'@'%' IDENTIFIED BY ?", []any{password}},
		{"GRANT ALL PRIVILEGES ON `" + name + "`.* TO '" + user + "'@'%'", nil},
	}
	for _, s := range stmts {
		if _, err := m.db.ExecContext(ctx, s.q, s.args...); err != nil {
			return fmt.Errorf("provision db: %w", err)
		}
	}
	return nil
}

func (m *MariaDB) DropSiteDB(ctx context.Context, name, user string) error {
	if !identRe.MatchString(name) || !identRe.MatchString(user) {
		return fmt.Errorf("invalid database identifier")
	}
	if _, err := m.db.ExecContext(ctx, "DROP DATABASE IF EXISTS `"+name+"`"); err != nil {
		return err
	}
	_, err := m.db.ExecContext(ctx, "DROP USER IF EXISTS '"+user+"'@'%'")
	return err
}

// SetConnectionLimit caps how many MariaDB connections a site's user may
// hold at once. Every site shares one server, so without this a single busy
// (or attacked) site can take all max_connections and knock every other
// site offline with "Error establishing a database connection".
func (m *MariaDB) SetConnectionLimit(ctx context.Context, user string, n int) error {
	if !identRe.MatchString(user) || n < 1 {
		return fmt.Errorf("invalid connection limit for %q", user)
	}
	_, err := m.db.ExecContext(ctx, "ALTER USER '"+user+"'@'%' WITH MAX_USER_CONNECTIONS "+strconv.Itoa(n))
	return err
}
