package site

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"time"

	"github.com/parthh37/wpgenie/internal/store"
)

// WordPress mail. The PHP image has no sendmail, so out of the box
// wp_mail() (password resets, order e-mails, contact forms) fails. With
// SMTP on, a site gets its own sender mailbox on the WPGenie mail server
// (see mail.Service.EnsureSender) and sends through it with SMTP AUTH,
// DKIM-signed.

// Mailer is the mail server as sites use it (mail.Service).
type Mailer interface {
	SMTPHost() string // "" when mail is off
	EnsureSender(ctx context.Context, siteID, domain string) (address, password string, err error)
	RemoveSender(ctx context.Context, siteID, domain string) error
}

const (
	smtpWrapperPath = "wp-content/mu-plugins/wpgenie-smtp.php"
	// smtpCredsFile lives next to wp-config.php, outside the docroot and
	// read-only to PHP (root:82 0640), inside the site's open_basedir.
	smtpCredsFile = "wpgenie-smtp.php"
)

const smtpWrapper = `<?php
/**
 * Plugin Name: WPGenie Mail
 * Description: Sends WordPress mail through the WPGenie mail server. Managed by WPGenie: toggle it in the WPGenie panel; this file is rewritten on changes.
 */
if ( is_file( '/usr/local/share/wpgenie/smtp.php' ) ) {
	require_once '/usr/local/share/wpgenie/smtp.php';
}
`

// Values are generated (address, host) or from passAlphabet, but checked
// anyway before being put in PHP single-quoted strings.
var phpSafe = regexp.MustCompile(`^[A-Za-z0-9@._+-]+$`)

var smtpDefineRe = regexp.MustCompile(`define\( 'WPGENIE_SMTP_(HOST|USER|PASS)', '([A-Za-z0-9@._+-]+)' \);`)

// parseSMTPCreds reads back a credentials file smtpCreds wrote.
func parseSMTPCreds(b []byte) (SMTPCreds, bool) {
	c := SMTPCreds{On: true}
	for _, m := range smtpDefineRe.FindAllSubmatch(b, -1) {
		switch string(m[1]) {
		case "HOST":
			c.Host = string(m[2])
		case "USER":
			c.Address = string(m[2])
		case "PASS":
			c.Password = string(m[2])
		}
	}
	return c, c.Host != "" && c.Address != "" && c.Password != ""
}

func smtpCreds(host, user, pass string) ([]byte, error) {
	for _, v := range []string{host, user, pass} {
		if !phpSafe.MatchString(v) {
			return nil, fmt.Errorf("unsafe SMTP credential value")
		}
	}
	return fmt.Appendf(nil, `<?php
// Generated by WPGenie: credentials for this site's mailbox %s.
define( 'WPGENIE_SMTP_HOST', '%s' );
define( 'WPGENIE_SMTP_USER', '%s' );
define( 'WPGENIE_SMTP_PASS', '%s' );
`, user, host, user, pass), nil
}

// SetSMTP turns sending WordPress mail through the WPGenie mail server on
// or off for a site.
func (s *Service) SetSMTP(ctx context.Context, id string, on bool) (*store.Site, error) {
	st, err := s.Store.GetSite(ctx, id)
	if err != nil {
		return nil, err
	}
	if s.Mailer == nil || (on && s.Mailer.SMTPHost() == "") {
		return nil, fmt.Errorf("%w: enable mail (a mail hostname) first", ErrInvalidInput)
	}
	lock := s.maintLock(id)
	if !lock.TryLock() {
		return nil, fmt.Errorf("%w: an update or scan is running on this site; try again when it finishes", ErrConflict)
	}
	defer lock.Unlock()
	if on {
		addr, pw, err := s.Mailer.EnsureSender(ctx, id, st.PrimaryDomain)
		if err != nil {
			return nil, err
		}
		if err := s.installSMTP(ctx, id, s.Mailer.SMTPHost(), addr, pw); err != nil {
			// Don't leave a mailbox behind for a site that isn't using it.
			c, cancel := context.WithTimeout(context.WithoutCancel(ctx), time.Minute)
			defer cancel()
			if !st.SMTP {
				err = errors.Join(err, s.Mailer.RemoveSender(c, id, st.PrimaryDomain))
			}
			return nil, err
		}
	} else {
		if err := s.removeSMTP(ctx, id); err != nil {
			return nil, err
		}
		if err := s.Mailer.RemoveSender(ctx, id, st.PrimaryDomain); err != nil {
			return nil, err
		}
	}
	msg := "WordPress mail now goes through the WPGenie mail server"
	if !on {
		msg = "WordPress mail through the WPGenie mail server turned off"
	}
	s.event(id, "mail", msg)
	return s.Store.GetSite(ctx, id)
}

func (s *Service) installSMTP(ctx context.Context, id, host, addr, pw string) error {
	creds, err := smtpCreds(host, addr, pw)
	if err != nil {
		return err
	}
	if err := s.writeSiteFile(id, smtpCredsFile, creds); err != nil {
		return err
	}
	if err := s.writeSMTPWrapper(id, true); err != nil {
		return err
	}
	return s.Store.SetSMTP(ctx, id, true)
}

// removeSMTP takes the site's mail credentials and wrapper away.
func (s *Service) removeSMTP(ctx context.Context, id string) error {
	if err := s.writeSMTPWrapper(id, false); err != nil {
		return err
	}
	if err := os.Remove(filepath.Join(s.Cfg.SiteDir(id), smtpCredsFile)); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return s.Store.SetSMTP(ctx, id, false)
}

func (s *Service) writeSMTPWrapper(id string, on bool) error {
	root, err := os.OpenRoot(s.Cfg.SiteRoot(id))
	if err != nil {
		return err
	}
	defer root.Close()
	return ensureManaged(root, smtpWrapperPath, smtpWrapper, on)
}

// writeSiteFile writes a root:82 0640 file into the site directory (next
// to wp-config.php, which the site can't write), atomically.
func (s *Service) writeSiteFile(id, name string, data []byte) error {
	dir := s.Cfg.SiteDir(id)
	tmp := filepath.Join(dir, "."+name+".tmp")
	if err := os.WriteFile(tmp, data, 0o640); err != nil {
		return err
	}
	if os.Geteuid() == 0 {
		if err := os.Chown(tmp, 0, wwwData); err != nil {
			os.Remove(tmp)
			return err
		}
	}
	return os.Rename(tmp, filepath.Join(dir, name))
}
