package site

import (
	"crypto/rand"
	"math/big"
	"strings"
	"text/template"
)

// wp-config.php is written by WPGenie rather than generated from env vars, so
// DB credentials never show up in `docker inspect` and hardening constants
// are always present.
var wpConfigTmpl = template.Must(template.New("wp-config").Parse(`<?php
/** Generated by WPGenie. Safe to edit below the marked line. */
define( 'DB_NAME',     '{{.DBName}}' );
define( 'DB_USER',     '{{.DBUser}}' );
define( 'DB_PASSWORD', '{{.DBPassword}}' );
define( 'DB_HOST',     '{{.DBHost}}' );
define( 'DB_CHARSET',  'utf8mb4' );
define( 'DB_COLLATE',  '' );
{{range .Salts}}
define( '{{.Name}}', '{{.Value}}' );{{end}}

$table_prefix = '{{.TablePrefix}}';

// --- WPGenie hardening ---
define( 'DISALLOW_FILE_EDIT', true );      // no PHP editing from wp-admin
define( 'FORCE_SSL_ADMIN', true );
define( 'WP_AUTO_UPDATE_CORE', 'minor' );  // security releases apply automatically
define( 'WP_POST_REVISIONS', 20 );
define( 'WP_REDIS_HOST', '{{.RedisHost}}' );
define( 'WP_REDIS_PREFIX', '{{.SiteID}}:' );
define( 'WP_CACHE_KEY_SALT', '{{.SiteID}}:' );
// --- end WPGenie ---

if ( ! defined( 'WP_DEBUG' ) ) {
	define( 'WP_DEBUG', false );
}
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
`))

type wpConfigData struct {
	SiteID, DBName, DBUser, DBPassword, DBHost, RedisHost, TablePrefix string
	Salts                                                              []salt
}

type salt struct{ Name, Value string }

var saltNames = []string{
	"AUTH_KEY", "SECURE_AUTH_KEY", "LOGGED_IN_KEY", "NONCE_KEY",
	"AUTH_SALT", "SECURE_AUTH_SALT", "LOGGED_IN_SALT", "NONCE_SALT",
}

func renderWPConfig(d wpConfigData) ([]byte, error) {
	for _, n := range saltNames {
		d.Salts = append(d.Salts, salt{n, randString(64, saltAlphabet)})
	}
	var b strings.Builder
	err := wpConfigTmpl.Execute(&b, d)
	return []byte(b.String()), err
}

const (
	// No quote or backslash: values are embedded in single-quoted PHP strings.
	saltAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#$%&()*+,-./:;<=>?@[]^_{|}~"
	lowerAlnum   = "abcdefghijklmnopqrstuvwxyz0123456789"
	passAlphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789"
)

func randString(n int, alphabet string) string {
	out := make([]byte, n)
	max := big.NewInt(int64(len(alphabet)))
	for i := range out {
		v, err := rand.Int(rand.Reader, max)
		if err != nil {
			panic(err)
		}
		out[i] = alphabet[v.Int64()]
	}
	return string(out)
}
