package store

// Migrations are written once, in SQLite's dialect, and translated to
// PostgreSQL mechanically when the store runs on Postgres:
//
//	INTEGER (any *INT* type), BOOLEAN   -> BIGINT (SQLite integers are 64-bit; booleans are 0/1)
//	INTEGER PRIMARY KEY [AUTOINCREMENT] -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
//	REAL, DOUBLE, FLOAT                 -> DOUBLE PRECISION
//	TEXT, VARCHAR(n), CHAR(n), CLOB     -> TEXT COLLATE "C" (byte order, as SQLite's BINARY)
//	TEXT ... COLLATE NOCASE             -> TEXT COLLATE wpgenie_nocase (case-insensitive
//	                                       equality, UNIQUE and ORDER BY, as in SQLite)
//	BLOB                                -> BYTEA
//	DEFAULT TRUE/FALSE                  -> DEFAULT 1/0
//	DEFAULT (strftime('%s','now')), DEFAULT (unixepoch())
//	                                    -> DEFAULT (CAST(EXTRACT(EPOCH FROM now()) AS BIGINT))
//	column names PostgreSQL reserves    -> quoted ("offset")
//	WITHOUT ROWID, STRICT, PRAGMA ...   -> dropped
//
// CREATE TABLE, CREATE [UNIQUE] INDEX, ALTER TABLE ... ADD COLUMN / RENAME
// / DROP COLUMN, DROP TABLE/INDEX and data statements (INSERT/UPDATE/
// DELETE, through the query rewriter) are understood. Anything else, or a
// type without a clear mapping (NUMERIC, DATETIME, no type at all), is an
// error naming the statement: give that migration a postgresMigrations
// override instead of guessing.

import (
	"errors"
	"fmt"
	"strings"
)

// nocaseCollation is created before the first migration runs on
// PostgreSQL: ICU, root locale, strength 2 (case-insensitive,
// accent-sensitive), non-deterministic so equality and UNIQUE follow it.
const nocaseCollation = `CREATE COLLATION IF NOT EXISTS wpgenie_nocase (provider = icu, locale = 'und-u-ks-level2', deterministic = false)`

// pgReserved are the words PostgreSQL does not accept as column names
// unquoted (reserved and type/function-name keywords), which SQLite
// happily does.
var pgReserved = map[string]bool{}

func init() {
	for _, w := range strings.Fields(`all analyse analyze and any array as asc asymmetric both case cast check
		collate column constraint create current_catalog current_date current_role current_time
		current_timestamp current_user default deferrable desc distinct do else end except false fetch for
		foreign from grant group having in initially intersect into lateral leading limit localtime
		localtimestamp not null offset on only or order placing primary references returning select
		session_user some symmetric system_user table then to trailing true union unique user using
		variadic when where window with
		authorization binary collation concurrently cross current_schema freeze full ilike inner is isnull
		join left like natural notnull outer overlaps right similar tablesample verbose`) {
		pgReserved[w] = true
	}
}

// translateMigration turns one SQLite migration script into PostgreSQL
// statements.
func translateMigration(script string) ([]string, error) {
	stmts, err := splitStatements(script)
	if err != nil {
		return nil, err
	}
	var out []string
	for n, st := range stmts {
		pg, err := translateStatement(st)
		if err != nil {
			return nil, fmt.Errorf("statement %d (%.60s…): %w", n+1, compact(st), err)
		}
		if pg != "" {
			out = append(out, pg)
		}
	}
	return out, nil
}

// splitStatements splits a script on top-level semicolons.
func splitStatements(script string) ([]string, error) {
	toks, err := tokenize(script)
	if err != nil {
		return nil, err
	}
	var out []string
	var b strings.Builder
	flush := func() {
		if s := strings.TrimSpace(b.String()); s != "" {
			out = append(out, s)
		}
		b.Reset()
	}
	for _, t := range toks {
		if t.kind == tkPunct && t.text == ";" {
			flush()
			continue
		}
		if t.kind == tkSpace && strings.HasPrefix(t.text, "--") {
			b.WriteString("\n") // comments go; they could hide a ';' from nobody but readers
			continue
		}
		b.WriteString(t.text)
	}
	flush()
	return out, nil
}

// sigToks returns the non-space tokens of a statement.
func sigToks(stmt string) ([]token, error) {
	toks, err := tokenize(stmt)
	if err != nil {
		return nil, err
	}
	var out []token
	for _, t := range toks {
		if t.kind != tkSpace {
			out = append(out, t)
		}
	}
	return out, nil
}

func translateStatement(stmt string) (string, error) {
	t, err := sigToks(stmt)
	if err != nil {
		return "", err
	}
	if len(t) == 0 {
		return "", nil
	}
	word := func(k int) string {
		if k < len(t) && t[k].kind == tkWord {
			return strings.ToLower(t[k].text)
		}
		return ""
	}
	switch word(0) {
	case "pragma":
		// Connection settings (foreign_keys, ...): PostgreSQL enforces
		// constraints always and has no equivalent to set.
		return "", nil
	case "insert", "update", "delete", "select", "with":
		return rewrite(stmt, true)
	case "drop":
		if w := word(1); w == "table" || w == "index" {
			return join(quoteReservedIdents(t)), nil
		}
	case "alter":
		if word(1) == "table" {
			return translateAlter(t)
		}
	case "create":
		k := 1
		if w := word(1); w == "temp" || w == "temporary" {
			return "", errors.New("temporary tables don't belong in migrations")
		}
		unique := word(k) == "unique"
		if unique {
			k++
		}
		switch word(k) {
		case "table":
			if !unique {
				return translateCreateTable(t)
			}
		case "index":
			return translateCreateIndex(t)
		}
	}
	return "", errors.New("the PostgreSQL translator doesn't handle this statement; add a postgresMigrations override")
}

// join renders tokens with single spaces (readable, and PostgreSQL
// doesn't care about layout).
func join(t []token) string {
	var b strings.Builder
	for i, tok := range t {
		if i > 0 && !(tok.text == "," || tok.text == ")" || tok.text == "." || t[i-1].text == "(" || t[i-1].text == ".") {
			b.WriteByte(' ')
		}
		b.WriteString(tok.text)
	}
	return b.String()
}

// ident renders a column or table name for PostgreSQL.
func ident(tok token) string {
	switch {
	case tok.kind == tkWord && pgReserved[strings.ToLower(tok.text)]:
		return quoteIdent(tok.text)
	case tok.kind == tkOther && (tok.text[0] == '`' || tok.text[0] == '['):
		return quoteIdent(tok.text[1 : len(tok.text)-1])
	}
	return tok.text
}

// quoteReservedIdents quotes bare names that PostgreSQL reserves where
// they stand as a name: after TABLE/INDEX/ON/EXISTS, or alone as a list
// item (between '(' or ',' and ',' , ')' , ASC, DESC or COLLATE).
func quoteReservedIdents(t []token) []token {
	out := append([]token(nil), t...)
	for i, tok := range t {
		if tok.kind != tkWord || !pgReserved[strings.ToLower(tok.text)] || i == 0 {
			if tok.kind == tkOther {
				out[i].text = ident(tok)
			}
			continue
		}
		prev := t[i-1]
		var next token
		if i+1 < len(t) {
			next = t[i+1]
		}
		named := prev.is("table") || prev.is("index") || prev.is("on") || prev.is("exists") || prev.is("column") ||
			prev.is("references") || prev.is("to")
		item := (prev.text == "(" || prev.text == ",") &&
			(next.text == "," || next.text == ")" || next.is("asc") || next.is("desc") || next.is("collate"))
		if named || item {
			out[i].text = quoteIdent(tok.text)
		}
	}
	return out
}

// mapCollations turns COLLATE NOCASE/BINARY into their PostgreSQL
// equivalents; RTRIM has none.
func mapCollations(t []token) ([]token, error) {
	var out []token
	for i := 0; i < len(t); i++ {
		if t[i].is("collate") && i+1 < len(t) {
			switch strings.ToLower(strings.Trim(t[i+1].text, `"`)) {
			case "nocase":
				out = append(out, t[i], token{tkWord, "wpgenie_nocase"})
			case "binary":
				out = append(out, t[i], token{tkQuoted, `"C"`})
			default:
				return nil, fmt.Errorf("COLLATE %s has no PostgreSQL equivalent", t[i+1].text)
			}
			i++
			continue
		}
		out = append(out, t[i])
	}
	return out, nil
}

func translateCreateIndex(t []token) (string, error) {
	// Expressions and WHERE clauses of partial indexes go through the
	// query rewriter's lint (no SQLite-only functions) by way of the
	// tokens; names get quoted where needed.
	sig := make([]int, len(t))
	for i := range sig {
		sig[i] = i
	}
	if err := lint(t, sig); err != nil {
		return "", err
	}
	t, err := mapCollations(quoteReservedIdents(t))
	if err != nil {
		return "", err
	}
	return join(t), nil
}

func translateAlter(t []token) (string, error) {
	// ALTER TABLE name ADD [COLUMN] def | RENAME ... | DROP [COLUMN] name
	if len(t) < 4 {
		return "", errors.New("incomplete ALTER TABLE")
	}
	head := []token{t[0], t[1], {tkWord, ident(t[2])}}
	rest := t[3:]
	switch {
	case rest[0].is("add"):
		def := rest[1:]
		if len(def) > 0 && def[0].is("column") {
			def = def[1:]
		}
		col, err := translateColumn(def)
		if err != nil {
			return "", err
		}
		return join(head) + " ADD COLUMN " + col, nil
	case rest[0].is("rename"), rest[0].is("drop"):
		return join(append(head, quoteReservedIdents(rest)...)), nil
	}
	return "", errors.New("unsupported ALTER TABLE form")
}

func translateCreateTable(t []token) (string, error) {
	// CREATE TABLE [IF NOT EXISTS] name ( defs ) [WITHOUT ROWID] [, STRICT]
	open := -1
	for i, tok := range t {
		if tok.text == "(" {
			open = i
			break
		}
		if tok.is("as") {
			return "", errors.New("CREATE TABLE ... AS SELECT: list the columns")
		}
	}
	if open < 3 {
		return "", errors.New("malformed CREATE TABLE")
	}
	head := append([]token(nil), t[:open]...)
	head[open-1] = token{tkWord, ident(head[open-1])}
	depth, start := 0, open+1
	var defs [][]token
	closeAt := -1
	for i := open; i < len(t) && closeAt < 0; i++ {
		switch t[i].text {
		case "(":
			depth++
		case ")":
			if depth--; depth == 0 {
				defs = append(defs, t[start:i])
				closeAt = i
			}
		case ",":
			if depth == 1 {
				defs = append(defs, t[start:i])
				start = i + 1
			}
		}
	}
	if closeAt < 0 {
		return "", errors.New("unbalanced parentheses")
	}
	for _, tok := range t[closeAt+1:] {
		if !tok.is("without") && !tok.is("rowid") && !tok.is("strict") && tok.text != "," {
			return "", fmt.Errorf("unsupported table option %s", tok.text)
		}
	}
	var cols []string
	for _, d := range defs {
		if len(d) == 0 {
			return "", errors.New("empty column definition")
		}
		if w := strings.ToLower(d[0].text); d[0].kind == tkWord &&
			(w == "primary" || w == "unique" || w == "foreign" || w == "check" || w == "constraint") {
			c, err := tableConstraint(d)
			if err != nil {
				return "", err
			}
			cols = append(cols, c)
			continue
		}
		c, err := translateColumn(d)
		if err != nil {
			return "", err
		}
		cols = append(cols, c)
	}
	return join(head) + " (\n\t" + strings.Join(cols, ",\n\t") + "\n)", nil
}

func tableConstraint(d []token) (string, error) {
	for i := 0; i+1 < len(d); i++ {
		if d[i].is("on") && d[i+1].is("conflict") {
			return "", errors.New("ON CONFLICT clauses in constraints are SQLite-only")
		}
		if d[i].is("check") {
			// CHECK expressions run through the query rewriter (LIKE,
			// IFNULL, SQLite-only functions).
			return rewrite(join(d), true)
		}
	}
	t, err := mapCollations(quoteReservedIdents(d))
	if err != nil {
		return "", err
	}
	return join(t), nil
}

// translateColumn translates "name type constraints...".
func translateColumn(d []token) (string, error) {
	if len(d) < 2 {
		return "", fmt.Errorf("column %s has no type (PostgreSQL needs one)", d[0].text)
	}
	name := ident(d[0])
	// The type runs until the first constraint keyword.
	k := 1
	var typ []string
	for ; k < len(d); k++ {
		w := strings.ToLower(d[k].text)
		if d[k].kind == tkWord && (w == "constraint" || w == "primary" || w == "not" || w == "null" || w == "unique" ||
			w == "check" || w == "default" || w == "collate" || w == "references" || w == "generated" || w == "as") {
			break
		}
		if d[k].text == "(" { // VARCHAR(255), DECIMAL(10, 2)
			for ; k < len(d) && d[k].text != ")"; k++ {
			}
			continue
		}
		typ = append(typ, strings.ToUpper(d[k].text))
	}
	ts := strings.Join(typ, " ")
	var pgType string
	integer := false
	switch {
	case ts == "":
		return "", fmt.Errorf("column %s has no type (PostgreSQL needs one)", d[0].text)
	case ts == "BOOLEAN" || ts == "BOOL":
		pgType, integer = "BIGINT", true
	case strings.Contains(ts, "INT"):
		pgType, integer = "BIGINT", true
	case strings.Contains(ts, "CHAR") || strings.Contains(ts, "CLOB") || strings.Contains(ts, "TEXT"):
		pgType = "TEXT"
	case ts == "BLOB":
		pgType = "BYTEA"
	case strings.Contains(ts, "REAL") || strings.Contains(ts, "FLOA") || strings.Contains(ts, "DOUB"):
		pgType = "DOUBLE PRECISION"
	default:
		return "", fmt.Errorf("column %s: type %s has no exact PostgreSQL mapping; use INTEGER, REAL, TEXT or BLOB", d[0].text, ts)
	}
	rest := d[k:]
	collation := ""
	if pgType == "TEXT" {
		collation = ` COLLATE "C"`
	}
	var out []token
	identity := false
	for i := 0; i < len(rest); i++ {
		tok := rest[i]
		next := func(n int) token {
			if i+n < len(rest) {
				return rest[i+n]
			}
			return token{}
		}
		switch {
		case tok.is("collate"):
			switch strings.ToLower(strings.Trim(next(1).text, `"`)) {
			case "nocase":
				collation = " COLLATE wpgenie_nocase"
			case "binary":
			default:
				return "", fmt.Errorf("column %s: COLLATE %s has no PostgreSQL equivalent", d[0].text, next(1).text)
			}
			if pgType != "TEXT" {
				return "", fmt.Errorf("column %s: COLLATE on a non-text column", d[0].text)
			}
			i++
		case tok.is("autoincrement"):
		case tok.is("primary") && next(1).is("key"):
			if integer && pgType == "BIGINT" {
				// SQLite's INTEGER PRIMARY KEY is the rowid: assigned when
				// an insert leaves it out, with or without AUTOINCREMENT.
				identity = true
			}
			out = append(out, tok, next(1))
			i++
			if next(1).is("asc") || next(1).is("desc") {
				i++
			}
		case tok.is("on") && next(1).is("conflict"):
			return "", fmt.Errorf("column %s: ON CONFLICT clauses in constraints are SQLite-only", d[0].text)
		case tok.is("generated") || tok.is("as"):
			return "", fmt.Errorf("column %s: generated columns need a postgresMigrations override", d[0].text)
		case tok.is("default"):
			v, n, err := translateDefault(rest[i+1:], integer)
			if err != nil {
				return "", fmt.Errorf("column %s: %w", d[0].text, err)
			}
			out = append(out, tok, token{tkWord, v})
			i += n
		case tok.is("check"):
			// CHECK (expr): through the query rewriter.
			depth, j := 0, i+1
			for ; j < len(rest); j++ {
				if rest[j].text == "(" {
					depth++
				} else if rest[j].text == ")" {
					if depth--; depth == 0 {
						break
					}
				}
			}
			if j >= len(rest) {
				return "", errors.New("unbalanced CHECK")
			}
			s, err := rewrite(join(rest[i:j+1]), true)
			if err != nil {
				return "", err
			}
			out = append(out, token{tkWord, s})
			i = j
		case tok.is("references") && i+1 < len(rest):
			out = append(out, tok, token{tkWord, ident(next(1))})
			i++
		default:
			if tok.kind == tkWord && i > 0 && (rest[i-1].text == "(" || rest[i-1].text == ",") &&
				pgReserved[strings.ToLower(tok.text)] {
				tok.text = quoteIdent(tok.text) // REFERENCES t(offset)
			}
			out = append(out, tok)
		}
	}
	col := name + " " + pgType
	if identity {
		col += " GENERATED BY DEFAULT AS IDENTITY"
	}
	col += collation
	if len(out) > 0 {
		col += " " + join(out)
	}
	return col, nil
}

// translateDefault translates the value after DEFAULT; it returns the
// PostgreSQL text and how many tokens it consumed.
func translateDefault(t []token, integer bool) (string, int, error) {
	if len(t) == 0 {
		return "", 0, errors.New("DEFAULT without a value")
	}
	switch {
	case t[0].is("true"):
		return "1", 1, nil
	case t[0].is("false"):
		return "0", 1, nil
	case t[0].is("null"), t[0].kind == tkString, t[0].kind == tkNumber:
		return t[0].text, 1, nil
	case (t[0].text == "-" || t[0].text == "+") && len(t) > 1 && t[1].kind == tkNumber:
		return t[0].text + t[1].text, 2, nil
	case t[0].is("current_timestamp"), t[0].is("current_date"), t[0].is("current_time"):
		return "", 0, errors.New("CURRENT_TIMESTAMP defaults differ between SQLite (text) and PostgreSQL; store unix seconds set by the code")
	case t[0].text == "(":
		depth := 0
		for j, tok := range t {
			if tok.text == "(" {
				depth++
			} else if tok.text == ")" {
				if depth--; depth == 0 {
					expr := strings.ToLower(strings.ReplaceAll(join(t[:j+1]), " ", ""))
					if integer && (expr == "(strftime('%s','now'))" || expr == "(unixepoch())" ||
						expr == "(unixepoch('now'))") {
						return "(CAST(EXTRACT(EPOCH FROM now()) AS BIGINT))", j + 1, nil
					}
					s, err := rewrite(join(t[:j+1]), true)
					return s, j + 1, err
				}
			}
		}
		return "", 0, errors.New("unbalanced DEFAULT expression")
	}
	return "", 0, fmt.Errorf("unsupported DEFAULT %s", t[0].text)
}
