package store

import (
	"strings"
	"testing"
)

func TestTranslateMigration(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{`CREATE TABLE t (
			id    INTEGER PRIMARY KEY AUTOINCREMENT,
			name  TEXT NOT NULL UNIQUE COLLATE NOCASE,
			ratio REAL NOT NULL DEFAULT 1,
			data  BLOB,
			on_   BOOLEAN NOT NULL DEFAULT TRUE,
			label VARCHAR(64) NOT NULL DEFAULT '',
			at    INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
			n     INT NOT NULL DEFAULT -1 CHECK (n >= -1),
			site  TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE
		)`, `CREATE TABLE t (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT COLLATE wpgenie_nocase NOT NULL UNIQUE,
	ratio DOUBLE PRECISION NOT NULL DEFAULT 1,
	data BYTEA,
	on_ BIGINT NOT NULL DEFAULT 1,
	label TEXT COLLATE "C" NOT NULL DEFAULT '',
	at BIGINT NOT NULL DEFAULT (CAST(EXTRACT(EPOCH FROM now()) AS BIGINT)),
	n BIGINT NOT NULL DEFAULT -1 CHECK (n >= - 1),
	site TEXT COLLATE "C" NOT NULL REFERENCES sites (id) ON DELETE CASCADE
)`},
		// Reserved words as names; composite keys; table options.
		{`CREATE TABLE IF NOT EXISTS ingest_state (
			name TEXT, offset INTEGER NOT NULL, user TEXT, "order" INTEGER,
			PRIMARY KEY (name, offset)
		) WITHOUT ROWID`, `CREATE TABLE IF NOT EXISTS ingest_state (
	name TEXT COLLATE "C",
	"offset" BIGINT NOT NULL,
	"user" TEXT COLLATE "C",
	"order" BIGINT,
	PRIMARY KEY (name, "offset")
)`},
		{`ALTER TABLE sites ADD COLUMN cpus REAL NOT NULL DEFAULT 1`,
			`ALTER TABLE sites ADD COLUMN cpus DOUBLE PRECISION NOT NULL DEFAULT 1`},
		{`ALTER TABLE sites ADD owner_id INTEGER REFERENCES users(id)`,
			`ALTER TABLE sites ADD COLUMN owner_id BIGINT REFERENCES users (id)`},
		{`ALTER TABLE users ADD COLUMN email TEXT NOT NULL DEFAULT '' COLLATE NOCASE`,
			`ALTER TABLE users ADD COLUMN email TEXT COLLATE wpgenie_nocase NOT NULL DEFAULT ''`},
		{`ALTER TABLE t RENAME COLUMN a TO offset`, `ALTER TABLE t RENAME COLUMN a TO "offset"`},
		{`ALTER TABLE t DROP COLUMN user`, `ALTER TABLE t DROP COLUMN "user"`},
		{`CREATE INDEX IF NOT EXISTS t_by_x ON t (site_id, offset DESC)`, `CREATE INDEX IF NOT EXISTS t_by_x ON t (site_id, "offset" DESC)`},
		{`CREATE UNIQUE INDEX u ON users (email COLLATE NOCASE) WHERE email <> ''`,
			`CREATE UNIQUE INDEX u ON users (email COLLATE wpgenie_nocase) WHERE email <> ''`},
		{`DROP INDEX IF EXISTS t_by_x`, `DROP INDEX IF EXISTS t_by_x`},
		{`DROP TABLE old`, `DROP TABLE old`},
		{`INSERT INTO b (id, n) SELECT id, IFNULL(n, 0) FROM a WHERE flag = TRUE`,
			`INSERT INTO b (id, n) SELECT id, COALESCE(n, 0) FROM a WHERE flag = 1`},
		{`UPDATE sites SET waf = 1 WHERE waf IS NULL`, `UPDATE sites SET waf = 1 WHERE waf IS NULL`},
		{`PRAGMA foreign_keys = OFF`, ``},
	} {
		got, err := translateMigration(c.in)
		if err != nil {
			t.Errorf("%s: %v", c.in, err)
			continue
		}
		if g := strings.Join(got, ";\n"); g != c.want {
			t.Errorf("translate(%s)\n got: %s\nwant: %s", c.in, g, c.want)
		}
	}
}

func TestTranslateMigrationSplitsStatements(t *testing.T) {
	got, err := translateMigration(`-- a comment; with a semicolon
		CREATE TABLE a (x TEXT DEFAULT 'a;b');
		ALTER TABLE a ADD COLUMN y INTEGER NOT NULL DEFAULT 0;

		CREATE INDEX a_y ON a (y);`)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 3 || !strings.Contains(got[0], `DEFAULT 'a;b'`) {
		t.Errorf("%q", got)
	}
}

// What the translator can't express is an error naming the problem, never
// a guess: the migration gets a postgresMigrations override.
func TestTranslateMigrationRefuses(t *testing.T) {
	for _, q := range []string{
		`CREATE TABLE t (a)`,                    // no type
		`CREATE TABLE t (a DATETIME)`,           // no exact mapping
		`CREATE TABLE t (a NUMERIC(10, 2))`,     // idem
		`CREATE TABLE t (a TEXT COLLATE RTRIM)`, // no equivalent
		`CREATE TABLE t (a TEXT DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE t (a INTEGER, b INTEGER GENERATED ALWAYS AS (a * 2))`,
		`CREATE TABLE t (a INTEGER PRIMARY KEY ON CONFLICT REPLACE)`,
		`CREATE TABLE t AS SELECT * FROM u`,
		`CREATE TRIGGER x AFTER INSERT ON t BEGIN SELECT 1; END`,
		`CREATE VIEW v AS SELECT 1`,
		`CREATE VIRTUAL TABLE f USING fts5(a)`,
		`INSERT OR REPLACE INTO t (a) VALUES (1)`,
		`CREATE TABLE t (a INTEGER DEFAULT (random()))`,
	} {
		if got, err := translateMigration(q); err == nil {
			t.Errorf("translated %s into %q", q, got)
		}
	}
}

// Every migration in the list translates (the PostgreSQL tests also run
// them; this catches a bad one without a database).
func TestAllMigrationsTranslate(t *testing.T) {
	for i := range migrations {
		if _, err := postgresStatements(i); err != nil {
			t.Errorf("migration %d: %v", i+1, err)
		}
	}
}
